### ISSUE TITLE
Unit tests failure in Debian Sid / Python 3.12

### ISSUE THREAD

**Issue by thomasgoirand** [zaneb/autopage#6]
Hi,

I'm getting the below unit tests failures when building v5.2.0 under Debian Sid. Please help me to solve them.

======================================================================
ERROR: test_exception (autopage.tests.test_end_to_end.InvokePagerTest.test_exception)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 286, in isolate
    yield env
  File "/<<PKGBUILDDIR>>/autopage/tests/test_end_to_end.py", line 226, in test_exception
    self.assertEqual(expected, pager.advance())
AssertionError: 23 != 179

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/test_end_to_end.py", line 220, in test_exception
    with isolation.isolate(with_exception) as env:
  File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 299, in isolate
    env.close(get_return_code)
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 99, in close
    self._exit_code = get_return_code()
                      ^^^^^^^^^^^^^^^^^
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 296, in get_return_code
    raise TestProcessNotComplete('\n'.join([result,
autopage.tests.isolation.TestProcessNotComplete: Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 263, in isolate
    raise TimeoutException(p.pid)
autopage.tests.isolation.TimeoutException: Test process 124224 timed out

======================================================================
ERROR: test_exit_pager_early (autopage.tests.test_end_to_end.InvokePagerTest.test_exit_pager_early)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 286, in isolate
    yield env
  File "/<<PKGBUILDDIR>>/autopage/tests/test_end_to_end.py", line 122, in test_exit_pager_early
    self.assertEqual(MAX_LINES_PER_PAGE, pager.advance())
AssertionError: 23 != 181

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/test_end_to_end.py", line 119, in test_exit_pager_early
    with isolation.isolate(infinite) as env:
  File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 299, in isolate
    env.close(get_return_code)
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 99, in close
    self._exit_code = get_return_code()
                      ^^^^^^^^^^^^^^^^^
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 296, in get_return_code
    raise TestProcessNotComplete('\n'.join([result,
autopage.tests.isolation.TestProcessNotComplete: Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 263, in isolate
    raise TimeoutException(p.pid)
autopage.tests.isolation.TimeoutException: Test process 124232 timed out

======================================================================
ERROR: test_interrupt_at_end_after_complete (autopage.tests.test_end_to_end.InvokePagerTest.test_interrupt_at_end_after_complete)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 286, in isolate
    yield env
  File "/<<PKGBUILDDIR>>/autopage/tests/test_end_to_end.py", line 173, in test_interrupt_at_end_after_complete
    self.assertEqual(num_lines, pager.total_lines())
AssertionError: 100 != 183

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/test_end_to_end.py", line 167, in test_interrupt_at_end_after_complete
    with isolation.isolate(finite(num_lines)) as env:
  File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 299, in isolate
    env.close(get_return_code)
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 99, in close
    self._exit_code = get_return_code()
                      ^^^^^^^^^^^^^^^^^
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 296, in get_return_code
    raise TestProcessNotComplete('\n'.join([result,
autopage.tests.isolation.TestProcessNotComplete: Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 263, in isolate
    raise TimeoutException(p.pid)
autopage.tests.isolation.TimeoutException: Test process 124240 timed out

======================================================================
ERROR: test_interrupt_early (autopage.tests.test_end_to_end.InvokePagerTest.test_interrupt_early)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 286, in isolate
    yield env
  File "/<<PKGBUILDDIR>>/autopage/tests/test_end_to_end.py", line 131, in test_interrupt_early
    self.assertEqual(MAX_LINES_PER_PAGE, pager.advance())
AssertionError: 23 != 185

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/test_end_to_end.py", line 128, in test_interrupt_early
    with isolation.isolate(infinite) as env:
  File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 299, in isolate
    env.close(get_return_code)
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 99, in close
    self._exit_code = get_return_code()
                      ^^^^^^^^^^^^^^^^^
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 296, in get_return_code
    raise TestProcessNotComplete('\n'.join([result,
autopage.tests.isolation.TestProcessNotComplete: Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 263, in isolate
    raise TimeoutException(p.pid)
autopage.tests.isolation.TimeoutException: Test process 124248 timed out

======================================================================
ERROR: test_interrupt_early_quit (autopage.tests.test_end_to_end.InvokePagerTest.test_interrupt_early_quit)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 286, in isolate
    yield env
  File "/<<PKGBUILDDIR>>/autopage/tests/test_end_to_end.py", line 144, in test_interrupt_early_quit
    self.assertEqual(MAX_LINES_PER_PAGE, pager.advance())
AssertionError: 23 != 187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/test_end_to_end.py", line 141, in test_interrupt_early_quit
    with isolation.isolate(infinite) as env:
  File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 299, in isolate
    env.close(get_return_code)
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 99, in close
    self._exit_code = get_return_code()
                      ^^^^^^^^^^^^^^^^^
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 296, in get_return_code
    raise TestProcessNotComplete('\n'.join([result,
autopage.tests.isolation.TestProcessNotComplete: Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 263, in isolate
    raise TimeoutException(p.pid)
autopage.tests.isolation.TimeoutException: Test process 124256 timed out

======================================================================
ERROR: test_interrupt_in_middle_after_complete (autopage.tests.test_end_to_end.InvokePagerTest.test_interrupt_in_middle_after_complete)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 286, in isolate
    yield env
  File "/<<PKGBUILDDIR>>/autopage/tests/test_end_to_end.py", line 156, in test_interrupt_in_middle_after_complete
    self.assertEqual(MAX_LINES_PER_PAGE, pager.advance())
AssertionError: 23 != 191

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/test_end_to_end.py", line 153, in test_interrupt_in_middle_after_complete
    with isolation.isolate(finite(num_lines)) as env:
  File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 299, in isolate
    env.close(get_return_code)
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 99, in close
    self._exit_code = get_return_code()
                      ^^^^^^^^^^^^^^^^^
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 296, in get_return_code
    raise TestProcessNotComplete('\n'.join([result,
autopage.tests.isolation.TestProcessNotComplete: Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 263, in isolate
    raise TimeoutException(p.pid)
autopage.tests.isolation.TimeoutException: Test process 124264 timed out

======================================================================
ERROR: test_page_to_end (autopage.tests.test_end_to_end.InvokePagerTest.test_page_to_end)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 286, in isolate
    yield env
  File "/<<PKGBUILDDIR>>/autopage/tests/test_end_to_end.py", line 97, in test_page_to_end
    self.assertEqual(expected, pager.advance())
AssertionError: 23 != 188

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/test_end_to_end.py", line 91, in test_page_to_end
    with isolation.isolate(finite(num_lines)) as env:
  File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 299, in isolate
    env.close(get_return_code)
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 99, in close
    self._exit_code = get_return_code()
                      ^^^^^^^^^^^^^^^^^
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 296, in get_return_code
    raise TestProcessNotComplete('\n'.join([result,
autopage.tests.isolation.TestProcessNotComplete: Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 263, in isolate
    raise TimeoutException(p.pid)
autopage.tests.isolation.TimeoutException: Test process 124271 timed out

======================================================================
ERROR: test_page_to_middle (autopage.tests.test_end_to_end.InvokePagerTest.test_page_to_middle)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 286, in isolate
    yield env
  File "/<<PKGBUILDDIR>>/autopage/tests/test_end_to_end.py", line 112, in test_page_to_middle
    self.assertEqual(MAX_LINES_PER_PAGE, pager.advance())
AssertionError: 23 != 190

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/test_end_to_end.py", line 109, in test_page_to_middle
    with isolation.isolate(finite(num_lines)) as env:
  File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 299, in isolate
    env.close(get_return_code)
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 99, in close
    self._exit_code = get_return_code()
                      ^^^^^^^^^^^^^^^^^
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 296, in get_return_code
    raise TestProcessNotComplete('\n'.join([result,
autopage.tests.isolation.TestProcessNotComplete: Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 263, in isolate
    raise TimeoutException(p.pid)
autopage.tests.isolation.TimeoutException: Test process 124278 timed out

======================================================================
ERROR: test_short_output (autopage.tests.test_end_to_end.InvokePagerTest.test_short_output)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 286, in isolate
    yield env
  File "/<<PKGBUILDDIR>>/autopage/tests/test_end_to_end.py", line 188, in test_short_output
    self.assertEqual(str(i), l.rstrip())
AssertionError: '0' != 'running test'
- 0
+ running test

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/test_end_to_end.py", line 184, in test_short_output
    with isolation.isolate(finite(num_lines)) as env:
  File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 299, in isolate
    env.close(get_return_code)
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 99, in close
    self._exit_code = get_return_code()
                      ^^^^^^^^^^^^^^^^^
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 296, in get_return_code
    raise TestProcessNotComplete('\n'.join([result,
autopage.tests.isolation.TestProcessNotComplete: Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 263, in isolate
    raise TimeoutException(p.pid)
autopage.tests.isolation.TimeoutException: Test process 124285 timed out

======================================================================
ERROR: test_short_output_reset (autopage.tests.test_end_to_end.InvokePagerTest.test_short_output_reset)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 286, in isolate
    yield env
  File "/<<PKGBUILDDIR>>/autopage/tests/test_end_to_end.py", line 197, in test_short_output_reset
    self.assertEqual(num_lines, pager.quit())
AssertionError: 10 != 179

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/test_end_to_end.py", line 194, in test_short_output_reset
    with isolation.isolate(finite(num_lines, reset_on_exit=True)) as env:
  File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 299, in isolate
    env.close(get_return_code)
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 99, in close
    self._exit_code = get_return_code()
                      ^^^^^^^^^^^^^^^^^
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 296, in get_return_code
    raise TestProcessNotComplete('\n'.join([result,
autopage.tests.isolation.TestProcessNotComplete: Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 263, in isolate
    raise TimeoutException(p.pid)
autopage.tests.isolation.TimeoutException: Test process 124293 timed out

======================================================================
ERROR: test_short_streaming_output (autopage.tests.test_end_to_end.InvokePagerTest.test_short_streaming_output)
----------------------------------------------------------------------
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 286, in isolate
    yield env
  File "/<<PKGBUILDDIR>>/autopage/tests/test_end_to_end.py", line 206, in test_short_streaming_output
    with env.stdin_pipe() as in_pipe:
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/test_end_to_end.py", line 203, in test_short_streaming_output
    with isolation.isolate(from_stdin, stdin_pipe=True) as env:
  File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 299, in isolate
    env.close(get_return_code)
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 99, in close
    self._exit_code = get_return_code()
                      ^^^^^^^^^^^^^^^^^
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 296, in get_return_code
    raise TestProcessNotComplete('\n'.join([result,
autopage.tests.isolation.TestProcessNotComplete: Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 263, in isolate
    raise TimeoutException(p.pid)
autopage.tests.isolation.TimeoutException: Test process 124301 timed out

======================================================================
ERROR: test_stderr_output (autopage.tests.test_end_to_end.InvokePagerTest.test_stderr_output)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 286, in isolate
    yield env
  File "/<<PKGBUILDDIR>>/autopage/tests/test_end_to_end.py", line 244, in test_stderr_output
    self.assertEqual(expected, pager.advance())
AssertionError: 23 != 188

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/test_end_to_end.py", line 238, in test_stderr_output
    with isolation.isolate(with_stderr_output) as env:
  File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 299, in isolate
    env.close(get_return_code)
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 99, in close
    self._exit_code = get_return_code()
                      ^^^^^^^^^^^^^^^^^
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 296, in get_return_code
    raise TestProcessNotComplete('\n'.join([result,
autopage.tests.isolation.TestProcessNotComplete: Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 263, in isolate
    raise TimeoutException(p.pid)
autopage.tests.isolation.TimeoutException: Test process 124309 timed out

======================================================================
ERROR: test_exit_early (autopage.tests.test_end_to_end.NoPagerTest.test_exit_early)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/test_end_to_end.py", line 268, in test_exit_early
    with isolation.isolate(infinite, stdout_pipe=True) as env:
  File "/usr/lib/python3.12/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 299, in isolate
    env.close(get_return_code)
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 99, in close
    self._exit_code = get_return_code()
                      ^^^^^^^^^^^^^^^^^
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 296, in get_return_code
    raise TestProcessNotComplete('\n'.join([result,
autopage.tests.isolation.TestProcessNotComplete: Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 263, in isolate
    raise TimeoutException(p.pid)
autopage.tests.isolation.TimeoutException: Test process 124317 timed out

======================================================================
ERROR: test_exit_early_buffered (autopage.tests.test_end_to_end.NoPagerTest.test_exit_early_buffered)
----------------------------------------------------------------------
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 286, in isolate
    yield env
  File "/<<PKGBUILDDIR>>/autopage/tests/test_end_to_end.py", line 279, in test_exit_early_buffered
    with env.stdin_pipe() as in_pipe:
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/test_end_to_end.py", line 277, in test_exit_early_buffered
    with isolation.isolate(from_stdin,
  File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 299, in isolate
    env.close(get_return_code)
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 99, in close
    self._exit_code = get_return_code()
                      ^^^^^^^^^^^^^^^^^
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 296, in get_return_code
    raise TestProcessNotComplete('\n'.join([result,
autopage.tests.isolation.TestProcessNotComplete: Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 263, in isolate
    raise TimeoutException(p.pid)
autopage.tests.isolation.TimeoutException: Test process 124325 timed out

======================================================================
ERROR: test_interrupt_early (autopage.tests.test_end_to_end.NoPagerTest.test_interrupt_early)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 286, in isolate
    yield env
  File "/<<PKGBUILDDIR>>/autopage/tests/test_end_to_end.py", line 293, in test_interrupt_early
    self.assertGreater(len(output), 0)
AssertionError: 0 not greater than 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/test_end_to_end.py", line 289, in test_interrupt_early
    with isolation.isolate(infinite, stdout_pipe=True) as env:
  File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 299, in isolate
    env.close(get_return_code)
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 99, in close
    self._exit_code = get_return_code()
                      ^^^^^^^^^^^^^^^^^
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 296, in get_return_code
    raise TestProcessNotComplete('\n'.join([result,
autopage.tests.isolation.TestProcessNotComplete: Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 263, in isolate
    raise TimeoutException(p.pid)
autopage.tests.isolation.TimeoutException: Test process 124333 timed out

======================================================================
ERROR: test_pipe_output_to_end (autopage.tests.test_end_to_end.NoPagerTest.test_pipe_output_to_end)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 286, in isolate
    yield env
  File "/<<PKGBUILDDIR>>/autopage/tests/test_end_to_end.py", line 263, in test_pipe_output_to_end
    self.assertEqual(num_lines, len(output))
AssertionError: 100 != 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/test_end_to_end.py", line 258, in test_pipe_output_to_end
    with isolation.isolate(finite(num_lines),
  File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 299, in isolate
    env.close(get_return_code)
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 99, in close
    self._exit_code = get_return_code()
                      ^^^^^^^^^^^^^^^^^
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 296, in get_return_code
    raise TestProcessNotComplete('\n'.join([result,
autopage.tests.isolation.TestProcessNotComplete: Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 263, in isolate
    raise TimeoutException(p.pid)
autopage.tests.isolation.TimeoutException: Test process 124340 timed out

======================================================================
ERROR: test_short_streaming_output (autopage.tests.test_end_to_end.NoPagerTest.test_short_streaming_output)
----------------------------------------------------------------------
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 286, in isolate
    yield env
  File "/<<PKGBUILDDIR>>/autopage/tests/test_end_to_end.py", line 301, in test_short_streaming_output
    with env.stdin_pipe() as in_pipe:
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/test_end_to_end.py", line 299, in test_short_streaming_output
    with isolation.isolate(from_stdin,
  File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 299, in isolate
    env.close(get_return_code)
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 99, in close
    self._exit_code = get_return_code()
                      ^^^^^^^^^^^^^^^^^
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 296, in get_return_code
    raise TestProcessNotComplete('\n'.join([result,
autopage.tests.isolation.TestProcessNotComplete: Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/autopage/tests/isolation.py", line 263, in isolate
    raise TimeoutException(p.pid)
autopage.tests.isolation.TimeoutException: Test process 124348 timed out

----------------------------------------------------------------------
Ran 153 tests in 34.426s

FAILED (errors=17)

**Comment by zaneb** [comment]
It [looks like](https://packages.debian.org/sid/less) Sid is still using less v590. I wonder if reverting de8bd4279630ea4b09e86d1d3ac443e0c7e29f6b would help (if so I'd definitely consider it a bug). The intention there was to work with all versions of less, but I suspect I was only able to test with v608 and v633.

I can't reproduce this on Fedora with Python 3.12.1 and less v633.

**Comment by zaneb** [comment]
Actually I can't reproduce with less v590 either (and it looks like I did test with that).

**Comment by zaneb** [comment]
I suspect that the setup.py you are using is not the one from https://github.com/zaneb/autopage/blob/deb/patches/setup_py.patch - that one has a [fix](https://github.com/zaneb/autopage/commit/970b268fed99f5a9384a667bb1524bc8f4a6063e) that is needed from version 0.5.0, and the latest in Sid is 0.4.0 so this is likely the first time you'd have run into it.
